<?php

namespace TransporteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CuentasCobrarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TteDespachoRepository extends EntityRepository
{
    public function listaDql($codigoEmpresa = "", $fechaDesde = "", $fechaHasta = "", $codigo = "") {
        $dql   = "SELECT d FROM TransporteBundle:TteDespacho d WHERE d.codigoEmpresaFk = $codigoEmpresa " ;  
        if($fechaDesde != "") {
            $dql .= " AND d.fecha >= '" . $fechaDesde . "'";
        }
        if($fechaHasta != "") {
            $dql .= " AND d.fecha <= '" . $fechaHasta . "'";
        }        
        if($codigo != "") {
            $dql .= " AND d.codigoDespachoPk = " . $codigo;
        }                 
        $dql .= " ORDER BY d.codigoDespachoPk DESC";
        return $dql;
    }     
}