<?php

namespace TransporteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CuentasCobrarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TteEmpresaRepository extends EntityRepository
{
    public function listaDql() {
        $dql   = "SELECT e FROM TransporteBundle:TteEmpresa e WHERE e.codigoEmpresaPk <> 0" ;            
        $dql .= " ORDER BY e.nombre ASC";
        return $dql;
    }          
}