<?php

namespace TransporteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CuentasCobrarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TteGuiaRepository extends EntityRepository
{
    public function listaDql($codigoEmpresa = "") {
        $dql   = "SELECT g FROM TransporteBundle:TteGuia g WHERE g.codigoEmpresaFk = $codigoEmpresa " ;            
        $dql .= " ORDER BY g.codigoGuiaPk DESC";
        return $dql;
    }     
    
    public function guiaPendienteDespachoDql($codigoEmpresa = "") {
        $dql   = "SELECT g FROM TransporteBundle:TteGuia g WHERE g.codigoEmpresaFk = $codigoEmpresa AND g.estadoDespachoProveedor = 0 " ;            
        $dql .= " ORDER BY g.codigoGuiaPk DESC";
        return $dql;
    }      
    
    public function guiasDespachoDql($codigoDespacho = "") {
        $dql   = "SELECT g FROM TransporteBundle:TteGuia g WHERE g.codigoDespachoProveedorFk = $codigoDespacho " ;            
        $dql .= " ORDER BY g.codigoGuiaPk DESC";
        return $dql;
    }      
}