<?php

namespace TransporteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CuentasCobrarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TteNoticiaRepository extends EntityRepository
{
    public function listaDql() {
        $dql   = "SELECT n FROM TransporteBundle:TteNoticia n WHERE n.codigoNoticiaPk <> 0" ;            
        $dql .= " ORDER BY n.codigoNoticiaPk DESC";
        return $dql;
    }          
}