<?php

namespace TransporteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CuentasCobrarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TtePrecioDetalleRepository extends EntityRepository
{
    public function listaDql($codigoEmpresa = "") {
        $dql   = "SELECT pd FROM TransporteBundle:TtePrecioDetalle pd WHERE pd.codigoEmpresaFk = $codigoEmpresa " ;            
        $dql .= " ORDER BY pd.codigoPrecioDetallePk DESC";
        return $dql;
    }     
}