# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        TransporteBundle\Entity\User:
            algorithm: bcrypt            
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]           
            
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: TransporteBundle:User
                property: username
                # if you're using multiple entity managers
                # manager_name: customer

    firewalls:       
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:    ^/
            http_basic: ~
            provider: our_db_provider  
            
            anonymous: ~
            form_login:
                login_path: login
                check_path: login 
            logout:
                path:   /logout
                target: /                
               
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            
    access_control:
        # require ROLE_ADMIN for /admin*
        #- { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/web, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_USER }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/recuperar, roles: IS_AUTHENTICATED_ANONYMOUSLY }        
        - { path: ^/cambiar/clave, roles: IS_AUTHENTICATED_ANONYMOUSLY }        
        - { path: ^/, roles: ROLE_USER }        